# Couldn't find class for name Placemaker
# Code Generated by ZenTest v. 4.2.1
#                 classname: asrt / meth =  ratio%
# YahooGeo::Placemaker::Query:    0 /    2 =   0.00%

require 'test/unit/testcase'
require 'test/unit' if $0 == __FILE__
require 'shoulda'
require 'yahoo_geo'
require 'placemaker/file_client'

module TestYahooGeo
  module TestPlacemaker
    class TestQuery < Test::Unit::TestCase
      context "Given a valid connection" do
        setup do
          YahooGeo::setup do
            placemaker_client YahooGeo::Placemaker::FileClient.new( 'test/response.xml' )
          end

          @query = YahooGeo::Placemaker::Query.new
        end

        should "Return a valid response" do
          response = @query.get( 1,2 ) #arguments don't matter... file_client
          assert_not_nil response
        end
      end
    end
  end
end

# Number of errors detected: 3
